kind: Deployment
apiVersion: apps/v1
metadata:
  name: cab-service

spec:
  replicas: 1
  selector:
    matchLabels:
      app: cab-service
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cab-service
    spec:
      containers:
        - name: cab-service-jlptq
          image: savaari/cab_service
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Never
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 1
  replicas: 1
  updatedReplicas: 1
  unavailableReplicas: 1
  conditions:
    - type: Available
      status: 'False'
      lastUpdateTime: '2021-04-11T14:20:11Z'
      lastTransitionTime: '2021-04-11T14:20:11Z'
      reason: MinimumReplicasUnavailable
      message: Deployment does not have minimum availability.
    - type: Progressing
      status: 'False'
      lastUpdateTime: '2021-04-11T14:30:15Z'
      lastTransitionTime: '2021-04-11T14:30:15Z'
      reason: ProgressDeadlineExceeded
      message: ReplicaSet "cab-service-844df67dfb" has timed out progressing.
